### ISSUE TITLE
Training time cost 

### ISSUE THREAD

**Issue by Amazingren** [sunshangquan/Histoformer#1]
Dear @sunshangquan ,

Thanks for your impressive work on adverse weather conditions. 

May I ask how long each training costs on one V100 (32G) GPU?

I am looking forward to hearing from you soon!

Best regards,

**Comment by sunshangquan** [comment]
Hi @Amazingren , each training takes nearly 6 days with 4 v100 (32G) GPU. Hope my reply helps.

**Comment by Amazingren** [comment]
> Hi @Amazingren , each training takes nearly 6 days with 4 v100 (32G) GPU. Hope my reply helps.

Got it. Thank you very much for your quick response!

Bests,
Bin
