### ISSUE TITLE
数据训练的问题

### ISSUE THREAD

**Issue by gejutaixiao22** [sunshangquan/Histoformer#14]
您好，我想询问一下模型中有关数据训练的部分。我注意到文中有三个任务，去雪，去雨雾以及去雨滴。我想询问一下这个程序是如何进行训练的。我注意到yml文件中是训练了一个数据集，并对每个数据集进行验证。请问真实训练时候是这样么。如果是的话那对哪个数据集进行训练呢。如果不是这样，那是分别对三个数据集进行训练并分别测试么，因为我也注意到三个数据集都有各自的训练集和测试集，如果是这样，RainDrop数据集我对test_a进行测试的。这是否正确呢。谢谢。

**Comment by sunshangquan** [comment]
您好，这个任务仿照的是transweather，把三个数据集的训练集混合起来一起训练，然后使用训练出来的一个模型分别对三个测试集测试。RainDrop数据集是对test_a进行测试

**Comment by gejutaixiao22** [comment]
那混在一起训练的是在您给的链接中Snow100K数据集么，我看这个数据集有个Allweather的txt文件，总共是18069张。

**Comment by sunshangquan** [comment]
训练集是三个数据集训练集的合集，使用的是[TransWeather](https://github.com/jeya-maria-jose/TransWeather?tab=readme-ov-file#train-data)和[All-in-One (CVPR 2020](https://openaccess.thecvf.com/content_CVPR_2020/papers/Li_All_in_One_Bad_Weather_Removal_Using_Architectural_Search_CVPR_2020_paper.pdf)提供的，请见[下载链接](https://drive.google.com/file/d/1tfeBnjZX1wIhIFPl6HOzzOKOyo0GdGHl/view?usp=sharing)
