### ISSUE TITLE
Install basicsr出现问题

### ISSUE THREAD

**Issue by pb-lang** [sunshangquan/Histoformer#15]
作者您好，我在使用python setup.py develop --no_cuda_ext命令后出现了以下问题
![image](https://github.com/user-attachments/assets/be45d099-6da7-48f9-99fc-c276afc58c62)

**Comment by sunshangquan** [comment]
您好，这个文件忘记上传了，不过我没有调试过setup.py，使用的就是Restorer的安装版本，可以参考这个[VERSION](https://github.com/swz30/Restormer/blob/main/VERSION)

**Comment by pb-lang** [comment]
> 您好，这个文件忘记上传了，不过我没有调试过setup.py，使用的就是Restorer的安装版本，可以参考这个[VERSION](https://github.com/swz30/Restormer/blob/main/VERSION)

作者您好，非常抱歉再次打扰您，我在raindrop数据集发现了两个测试集，请问你使用了哪个测试集进行测试

![image](https://github.com/user-attachments/assets/8c59b990-9d13-43b6-91ca-51ab4f90607c)

**Comment by sunshangquan** [comment]
Sorry for the late reply. Please refer to [Issue 10](https://github.com/sunshangquan/Histoformer/issues/10). ```test_a``` is used for quantitative evaluation.

**Comment by pb-lang** [comment]
> Sorry for the late reply. Please refer to [Issue 10](https://github.com/sunshangquan/Histoformer/issues/10). `test_a` is used for quantitative evaluation.

Thanks
