### ISSUE TITLE
DHSA模块中为何将BHR和FHR的输出进行逐元素相乘

### ISSUE THREAD

**Issue by DarkIceField** [sunshangquan/Histoformer#20]
作者您好，感谢您分享并开源您的优秀工作。我对您的网络结构中DHSA模块中将BHR和FHR的输出进行逐元素相乘这一操作感到有些疑惑。因为在我的理解里，BHR和FHR模块输出的都是从图像中提取的特征，而不是某种权重矩阵。似乎很少见到有网络结构会对不同模块获得的特征进行逐元素相乘操作来进行特征的融合。能请您分享一下在设计这个操作时候的想法和动机吗？

**Comment by sunshangquan** [comment]
Hi @DarkIceField ，逐元素点乘可以理解为类似于一种门控机制，而BHR和FHR的输出则包含了不同尺度范围的特征，最初的想法是将其二者进行融合，在实验中发现相加、concat后降维、点乘三种方式的性能差不多，相加的话就成了两倍的特征，动机可能不太好解释，而concat后降维需要更多计算量，因此综合起来看点乘可能略好一些，希望可以帮到您

**Comment by DarkIceField** [comment]
> Hi @DarkIceField ，逐元素点乘可以理解为类似于一种门控机制，而BHR和FHR的输出则包含了不同尺度范围的特征，最初的想法是将其二者进行融合，在实验中发现相加、concat后降维、点乘三种方式的性能差不多，相加的话就成了两倍的特征，动机可能不太好解释，而concat后降维需要更多计算量，因此综合起来看点乘可能略好一些，希望可以帮到您

非常感谢您的回复，祝您科研顺利！
