### ISSUE TITLE
About data clipping

### ISSUE THREAD

**Issue by liu645liu** [sunshangquan/Histoformer#22]
Hello, sorry to bother you. When we were training the network to epoch 118, a downsampling error occurred, showing RuntimeError: pixel_unshuffle expects height to be divisible by downscale_factor, but input.size(-2)=181 is not divisible by 2. However, it was normal before this round. I would like to ask whether the experiment was operated at epoch 118. As shown in the figure, bs_j here has a value of 3 when the iteration round is 268000. It prints logger.info('\n Updating Patch_Size to {} and Batch_Size to {} \n'.format(mini_gt_size,
mini_batch_size * torch.cuda.device_count()))
logger_j[bs_j] = False
, which is False at this time. Then does it cause the following data to not be operated so that 181 cannot be divided by 2? But I don't quite understand what this logic is. Can you help me see it?
![f51012bb9850770fb4745b3e21b37c96](https://github.com/user-attachments/assets/b16c8bfb-d1b7-4164-a65b-7cca74095a48)
![11e99d69baa5c9b601f25e3c88c20e9a](https://github.com/user-attachments/assets/7d9807f7-0373-4f30-b88e-65c421090a51)

**Comment by Bruce-W12138** [comment]
I have the same question, how can you solve that
