### ISSUE TITLE
關於PSNR的計算方式

### ISSUE THREAD

**Issue by WUKUNTAI-0211** [sunshangquan/Histoformer#5]
Shangquan Sun，您好! 感謝您出色的作品!

有兩個問題想跟您確認，
1.請問論文中的psnr分數是只計算在Y channel上嗎?
2.請問計算psnr的方式是使用Restormer中的[evaluate_PSNR_SSIM.m](https://github.com/swz30/Restormer/blob/main/Deraining/evaluate_PSNR_SSIM.m)，或是在python 中計算呢? 因為這兩種出來的分數會有點不一致

期待收到您的回覆!!

**Comment by sunshangquan** [comment]
Hi, @Jerry-Jimmy , 和前人一样，psnr的计算都是在y通道上计算的，没有使用Restormer中的[evaluate_PSNR_SSIM.m](https://github.com/swz30/Restormer/blob/main/Deraining/evaluate_PSNR_SSIM.m)，使用的是python代码，我这两天更新一下

**Comment by sunshangquan** [comment]
Hi @Jerry-Jimmy I have uploaded ```compute_psnr.py``` for reproduction. Please refer to this [place](https://github.com/sunshangquan/Histoformer/tree/main?tab=readme-ov-file#balance_scale-evaluation).

**Comment by WUKUNTAI-0211** [comment]
Thank you!!
