### ISSUE TITLE
Testset of Outdoor-Rain

### ISSUE THREAD

**Issue by dsjiaod** [sunshangquan/Histoformer#8]
很棒的工作！
方便的话请问能提供一下Outdoor-Rain的测试集吗？我在我之前下载的测试集上，下载了您提供的visual results，用您提供的evaluation psnr和ssim的code测试Histoformer的性能，结果是31.673093507886737 0.929211313578245，与paper中的结果有较大差异，可能是我的测试集和您用的不一致。希望您能提供使用的测试集，方便我在paper中进行公平对比，感谢！

**Comment by sunshangquan** [comment]
Hi @dsjiaod , Thank you for your interest and attention. I have checked the test set of Outdoor-Rain, i.e., Test1, again. The original one from [1] has expired according to [2]
The current Test1 of 750 pairs is from TransWeather. There is a [text file](https://drive.google.com/file/d/1UsazX-P3sPcDGw3kxkyFWqUyNfhYN_AM/view) listing all 750 pairs of images. I have also uploaded its [image files](https://drive.google.com/file/d/1xgLG6656ahL7TfpeO_TplkMOQrfdxKbo/view?usp=sharing). By the way, please make sure to use "net_g_best.pth".

[1] Heavy Rain Image Restoration: Integrating Physics Model and Conditional Adversarial Learning
[2] https://github.com/liruoteng/HeavyRainRemoval/issues/18

**Comment by dsjiaod** [comment]
@sunshangquan 谢谢您的回复，我并没有运行histoformer的模型，而是从您Google Drive中提供的visual results下载了结果进行evaluation。在raindrop数据集我能得到与论文中一致的指标，但是在outdoor-rain数据集上，我用您提供的这个测试集里的GT进行测试，依然得到的是我上面提到的结果（31.673093507886737 0.929211313578245），我是用您提供的[compute_psnr.py](https://github.com/sunshangquan/Histoformer/blob/main/Allweather/compute_psnr.py)进行的计算，请问是我哪个步骤有误么？

**Comment by sunshangquan** [comment]
@dsjiaod ，那应该是我传错文件夹版本了，下午更新一下，您方便的话可以先尝试用test_histoformer.py跑出结果，我刚刚又跑了一遍，psnr是接近32.09的结果

**Comment by dsjiaod** [comment]
@sunshangquan 好的，您有更新结果麻烦提醒下我，我也试着跑一下net_g_best的inference

**Comment by dsjiaod** [comment]
@sunshangquan 我刚刚测试了一下net_g_best，没有问题了，谢谢您的帮助
